# -*- coding: utf-8 -*-
"""CLI_Based_Conversational_Chatbot_llama_mistral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mk1aNW7IncwjrppG9-VGjr1yEDW82f9a
"""

!pip install huggingface_hub transformers torch accelerate

from huggingface_hub import login
login()

from transformers import AutoTokenizer
model_name = "mistralai/Mistral-7B-v0.1"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=True)

from transformers import pipeline
import torch

pipeline = pipeline(
    "text-generation",  # LLM task
    model=model_name,
    torch_dtype=torch.float16,
    device_map="auto",
)

chat_history = []

def get_llm_response(prompt: str) -> None:
    """
    Generate a response from the Llama model.

    Parameters:
        prompt (str): The user's input/question for the model.

    Returns:
        None: Prints the model's response.
    """
    global chat_history
    chat_history.append(f"User: {prompt}")
    sequences = pipeline(
        prompt,
        do_sample=True,
        top_k=2,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=256,
    )

    ai_assistant_response=sequences[0]['generated_text'].split("Assistant:")[-1].strip()
    chat_history.append(f"Assistant: {ai_assistant_response}")
    print("Chatbot:", ai_assistant_response)

prompt = 'I liked "Breaking Bad" and "Band of Brothers". Do you have any recommendations of other shows I might like?\n'
get_llm_response(prompt)

prompt = """I'm a programmer and Python is my favorite language because of it's simple syntax and variety of applications I can build with it.\
Based on that, what language should I learn next?\
Give me 5 recommendations"""
get_llm_response(prompt)

while True:
    user_input = input("You: ")
    if user_input.lower() in ["bye", "quit", "exit"]:
        print("Chatbot: Goodbye!")
        break
    get_llm_response(user_input)